Emacs Usage Tips

* Keys
  - =M-x fixup-whitespace= collapses all but one space.
  - Open multiple info buffers by giving a prefix argument to info, e.g., =C-u 5 C-h i=.
  - Press =C-h= after a key prefix to see all the keys defined for
    that prefix. For example, =C-x C-h= shows all keys bound with a
    prefix of =C-x=. Ditto for =C-c C-h=.
  - =C-S-backspace= runs =kill-whole-line=, which is very useful.
  - =C-c i= from Prelude runs =imenu= with =ido=.
  - =C-u C-h i= to open up a specific Info file. =C-x C-f= followed by
    =M-x Info-mode= will /not/ work.
  - =C-c i= runs =prelude-ido-goto-symbol=, which invokes =imenu=.
  - =C-x -= shrinks the window to the size of the buffer.
* Miscellaneous
  - For defining a new translation key, look at this [[http://www.emacswiki.org/emacs/PrefixKey#toc2][link on the EmacsWiki]].
  - Use directory variables by creating a =.dir-locals.el= file.
  - Use registers and bookmarks
  - Use keyboard macros (=start-kb-macro=, =end-kbd-macro=,
    =call-last-kbd-macro=, etc. =C-h a kbd-macro= too see all)
  - Use more snippets (and include Emacs Lisp transforms)
  - Use expand-region, helm, and projectile.
  - Imenu allows jumping to a symbol in a buffer (such as a function
    in C or Python). It's awesome, and should be used heavily.
  - =M-x overwrite-mode= to get overtype (insert key) in Emacs. Knew
    this had to be somewhere; took me long enough to find it.
  - When using Skim, activate backward search with Command-Shift-Click.
  - Use =flush-lines= and =keep-lines= to filter lines in a file based on regex.
* Aquamacs
  - Using Aquamacs, Skim, and SyncTeX together allows forward and
    backward jumping through the TeX source and output. But it's only
    working with *my config* when I change the View command in
    =TeX-command-list= from =TeX-run-discard-or-function= to
    =TeX-run-function=. Not sure how to fix this yet. See
    =personal-tex.el= for a description of the problems.
  - If Aquamacs dies and you get the "Send Error Report" dialog, this
    can cause nightly builds (as of 2012-12-08) to crash when the dialog
    buttons are clicked. Directly run the executable in the app bundle
    to see the errors. To fix it, I put Aquamacs-2.4 back into
    /Applications, opened Aquamacs, closed the dialogs, then put nightly
    Aquamacs back into /Applications (overwriting 2.4). Ugly, but it
    works.
  - Press =C-;= to toggle whether Option key means Meta or Option. This
    can be used to get rid of the annoying insertion of symbols when I
    tap it accidentally.
** When rebuilding the config for Aquamacs, you can...
  - Check progress by looking at the **Window** menu. There should be a bunch of =*-autoloads.el= open. As long as those keep opening, it's going good. When a backtrace buffer appears, it started failing.
  - If it looks like nothing is happening, clicking **About Aquamacs** can be used to bring up a frame.
* Emacs Lisp
  - Use =M-x finder-list-keywords= to get a list of keywords that can be
    used in Emacs Lisp file headers.
  - AFAIK, it's not really possible to automatically autoload vendorized code.
* Startup
  - zsh adds a bunch of entries to the MANPATH that it somehow
    finds. Starting Emacs from zsh on my Mac OS X allows man and WoMan
    to find a bunch more manuals than starting from bash.
